version: "3.7"

volumes:
  teste_mysql_data:
    driver: local

networks:
  teste_network:
    driver: bridge

services:
  php:
    build: ./docker/php
    container_name: teste_php
    working_dir: /var/www/
    networks: 
      - teste_network
    volumes:
      - ./:/var/www/
      - ./docker/configs/supervisor/laravel_worker.conf:/etc/supervisor/conf.d/laravel_worker.conf:ro



  nginx:
    build: ./docker/nginx
    container_name: teste_nginx
    working_dir: /var/www/
    networks: 
      - teste_network
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf

  mysql:
    build: ./docker/mysql
    container_name: teste_mysql
    networks: 
      - teste_network
    environment:
      - MYSQL_DATABASE=teste
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_USER=docker
      - MYSQL_PASSWORD=secret
    volumes:
      - teste_mysql_data:/var/lib/mysql

  # python:
  #   image: python:3.6
  #   container_name: teste_python
  #   working_dir: /var/www/
  #   networks: 
  #     - teste_network

  mailhog:
    build: ./docker/mailhog
    container_name: teste_mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - teste_network
