version: "3.7"

volumes:
  teste_mysql_data:
    driver: local

networks:
  teste_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.2.0.0/16

services:
  php:
    build: ./docker/php
    container_name: teste_php
    working_dir: /var/www/
    networks: 
      - teste_network
    volumes:
      - ./:/var/www/

  supervisor:
    build: ./docker/supervisor
    container_name: teste_supervisor
    working_dir: /var/www/
    networks:
      - teste_network
    volumes:
      - ./:/var/www/
      - ./docker/configs/supervisor:/etc/supervisor/conf.d/
    depends_on:
      - php
      - nginx

  nginx:
    build: ./docker/nginx
    container_name: teste_nginx
    working_dir: /var/www/
    networks:
      - teste_network
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf

  mysql:
    build: ./docker/mysql
    container_name: teste_mysql
    networks: 
        teste_network:
          ipv4_address: 10.2.0.5
    environment:
      - MYSQL_DATABASE=teste
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_USER=docker
      - MYSQL_PASSWORD=secret
    volumes:
      - teste_mysql_data:/var/lib/mysql

  mailhog:
    build: ./docker/mailhog
    container_name: teste_mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - teste_network
